namespace NodeJS {
  interface ProcessEnv {
    DATABASE_URL: string

    NEXTAUTH_SECRET: string
    NEXTAUTH_URL: string

    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string

    EMAIL_SERVER_USER: string
    EMAIL_SERVER_PASSWORD: string
    EMAIL_SERVER_HOST: string
    EMAIL_SERVER_PORT: string
    EMAIL_FROM: string

    NEXT_PUBLIC_CLOUDINARY_BASE_URL: string
    NEXT_PUBLIC_CLOUDINARY_VIDEO_BASE_URL: string
    NEXT_PUBLIC_CLOUDINARY_FOLDER: string

    NEXT_PUBLIC_BASE_URL: string
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: string

    NEXT_PUBLIC_CLOUDINARY_API_KEY: string
    NEXT_PUBLIC_CLOUDINARY_API_SECRET: string
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string

    NEXT_PUBLIC_CLOUDINARY_BASE_URL: string
    NEXT_PUBLIC_CLOUDINARY_VIDEO_BASE_URL: string
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: string
    NEXT_PUBLIC_CLOUDINARY_API_KEY: string
    NEXT_PUBLIC_CLOUDINARY_API_SECRET: string
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string
    NEXT_PUBLIC_CLOUDINARY_FOLDER: string

    NEXT_PUBLIC_BASE_URL: string
  }
}
