version: '3.8'

services:
  postgres:
    container_name: db
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db
    volumes:
      - postgres-data:/bitnami/postgresql
    hostname: postgres-server

volumes:
  postgres-data:
